#!/usr/bin/perl -w
# -*- perl -*-

=head1 NAME

dapnet - Plugin to trace the DAPNET core usage

=head1 CONFIGURATION

The following environment variables are NOT used right now

 host      - DAPNET hostname to query (default undef)
 port      - DAPNET  port to use (default 8080)

=head1 AUTHOR

Copyright (C) 2017 Ralf Wilke

=head1 LICENSE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2 dated June,
1991.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

=head1 BUGS

NONE

=cut



use strict;
use JSON qw( decode_json );
use LWP::UserAgent;
use HTTP::Request::Common;
use v5.10;
use Munin::Plugin;


my $host      = $ENV{host}      || "dapnet.db0sda.ampr.org";
my $port      = $ENV{port}      || 8080;


if (defined $ARGV[0] and $ARGV[0] eq "config")
{
        print "host_name $host\n" unless $host eq 'localhost';
        print "graph_title DAPNET Statistics\n";
        print "graph_args --lower-limit 0\n";
#        print "graph_vlabel %\n";
        print "graph_category DAPNET\n";
        print "graph_info This graph the DAPNET statistics.\n";

        print ("users.label Users\n");
        print ("users.info Registered users\n");
        print ("calls.label Calls\n");
        print ("calls.info Calls sent out\n");
        print ("nodesTotal.label Nodes total\n");
        print ("nodesTotal.info Registered nodes in total\n");
        print ("nodesOnline.label Online nodes\n");
        print ("nodesOnline.info Nodes that are online\n");
        print ("transmittersTotal.label Transmitters Total\n");
        print ("transmittersTotal.info Registered transmitters in total\n");
        print ("transmittersOnline.label Online transmitters\n");
        print ("transmittersOnline.info Transmitters that are online\n");

        exit 0;
}


my $ua = LWP::UserAgent->new();
my $url = "http://" . $host . ":" . $port . "/stats";
my $request = GET $url;
#my $request = GET 'http://dapnet.db0sda.ampr.org:8080/stats';

my $response = $ua->request($request);
my $json_content = $response->content;

#print $json_content;
my $decodedjson = decode_json($json_content);
print ("users.value ");
print $decodedjson->{"users"};
print ("\n");
print ("calls.value ");
print $decodedjson->{"calls"};
print ("\n");
print ("nodesTotal.value ");
print $decodedjson->{"nodesTotal"};
print ("\n");
print ("nodesOnline.value ");
print $decodedjson->{"nodesOnline"};
print ("\n");
print ("tranmittersTotal.value ");
print $decodedjson->{"transmittersTotal"};
print ("\n");
print ("tranmittersOnline.value ");
print $decodedjson->{"transmittersOnline"};
print ("\n");
